name: DEST TAST
run-name: ${{ github.actor }} is testing out DAST Actions 
on:
  # workflow_dispatch:
  push:
    branches:
      - "test"
jobs:
  Fortify-DAST:
    runs-on: kenlin
    steps:
    - name: testpipe
      run: |
        echo "AUTH_RESP=$(curl -X 'POST' -s --insecure 'https://172.16.67.168:5001/api/v2/auth' -H 'accept:text/plain' -H 'Content-Type:application/json-patch+json' -d "{'username':'admin', 'password':'Netpoleon#1'}")" >> $GITHUB_ENV
        echo "$AUTH_RESP"
        echo "FFTOKEN=$(echo $AUTH_RESP| grep -o '"token":"FORTIFYTOKEN [^"]\+' | cut -d '"' -f 4)" >> $GITHUB_ENV
        echo "$FFTOKEN"
        curl -X 'POST' -I -s --insecure 'https://172.16.67.168:5001/api/v2/scans/start-scan-cicd' -H 'accept:text/plain' -H "Authorization:$env.FFTOKEN" -H 'Content-Type:application/json-patch+json' -d "{'cicdToken':'4ebc1b34-be5e-48f3-981a-ba4e16e9891f','name':'testcicd','scannerId':0,'useAssignedScannerOnly':true,'overrides':{'dataRetentionDays':0,'scanPriority':5,'scanMode':2}}"
        
