name: Test DAST
run-name: ${{ github.actor }} is testing out DAST Actions 
on:
  workflow_dispatch:
jobs:
  Fortify-DAST:
    runs-on: kenself
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Love Netpoleons"
