name: Lin DAST
run-name: ${{ github.actor }} is testing out DAST Actions 
on:
  workflow_dispatch:
jobs:
  Fortify-DAST:
    runs-on: kenlin
    steps:
    - name: testlinpipe  
      run:
        echo "this linux work"
